set nocompatible
"execute pathogen#infect()
filetype plugin indent on
syntax on

set encoding=utf-8
set ignorecase

" show line numbers
set number 

" show command in bottom bar
set showcmd

" :help laststatus
set laststatus=2


highlight! link DiffText MatchParen
