all:

pune:
	mkdir -p ~/.config/redshift
	cd ~/.config/redshift && ln -s ~/configs/redshift/pune_redshift.conf redshift.conf

kolkata:
	mkdir -p ~/.config/redshift
	cd ~/.config/redshift && ln -s ~/configs/redshift/kolkata_redshift.conf redshift.conf
