# -*- mode:Shell-script -*-

# Check for an interactive session
[ -z "$PS1" ] && return

#source /usr/etc/profile.d/autojump.bash

source ~/.bash.aliases
source ~/.bash.functions

# https://raw.githubusercontent.com/paoloantinori/hhighlighter/master/h.sh
source ~/.h.sh

[[ -f /usr/share/git/completion/git-prompt.sh ]] && source /usr/share/git/completion/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1 GIT_PS1_SHOWSTASHSTATE=1
TITLEBAR="\e]2\u@\h:\w\a"
PS1='\e]2\u@\h:\w\a\u@\h \w$(__git_ps1 " (%s)")\n\$ '
PS1='\e]2\u@\h:\w\a\u@\h \w$(__git_ps1 " (%s - $(git rev-parse --short HEAD 2>/dev/null))")\n\$ '
#PS1="[\u@\h \w$(__git_ps1 " (%s)")]$(tput sgr0)\n\$ "


#http://stackoverflow.com/questions/103944/real-time-history-export-amongst-bash-terminal-windows
#export PROMPT_COMMAND='history -a; history -n; history -w'
#export PROMPT_COMMAND="$PROMPT_COMMAND; history -a; history -n; history -w"
export HISTCONTROL=ignoreboth:erasedups

#export HISTIGNORE="pwd:ls:cd:l:e:yy:yu:history:tmux:lrt:cls" I think
# using HISTIGNORE is not such a good thing. Sometimes I want to see
# what was the previous command for whatever the reason. I think a
# better approach is to prune the history later.

export HISTSIZE=100000
export HISTFILESIZE=100000
HISTTIMEFORMAT='%F %T  '
shopt -s histappend
shopt -s dotglob
shopt -s extglob
shopt -s globstar
shopt -s checkwinsize
shopt -s histverify
#export EDITOR=~/bin/e

PATH=$PATH:~/.local/bin:~/anaconda3/bin

export LESSOPEN='|src-hilite-lesspipe.sh %s'
export LESS='-R'

#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/ap_root/lib

# PDTK 
export PYTHONPATH=${PYTHONPATH}:~/work/predictika/predictibot.com/pbot
#export MODE=DEV
export MODE=TEST
export NLTK_DATA=/usr/share/nltk_data
export PBOT_DOMAIN=localhost
export PDTK_HOME=~/work/predictika/predictibot.com

# vim: ft=sh syn=sh
